# Prometheus configuration for TechWave stack on Linux

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]

  # Scrape Flask app running on the host
  - job_name: "flask-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["172.17.0.1:5000"]   # Reemplaza con la IP real del host docker0
        labels:
          app: flask-app

  # Scrape Loki metrics
  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]
        labels:
          app: loki
