replicaCount: 1

image:
  repository: lumuma2025/techwave_web_k8s
  tag: 1.0.0
  pullPolicy: Always

env:
  FLASK_ENV: development
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

ingress:
  enabled: false
