replicaCount: 2
version: green
image:
  repository: lumuma2025/techwave_web_k8s
  tag: 1.0.0
  pullPolicy: Always

env:
  FLASK_ENV: development
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"

service:
  type: loadBalancer
  port: 5000

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false
