name: Build and Deploy Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir imagen con tag dinámico (commit SHA)
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}  # 8 primeros caracteres del SHA
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Push imagen al registry
      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG

      # 4.15. Listar archivos para verificar ruta
      - name: List repo files
        run: ls -R $GITHUB_WORKSPACE

      # 5. Actualizar Helm values.yaml con la nueva versión
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" $GITHUB_WORKSPACE/helm/flask-app/values.yaml

      # 6. Configurar Git para push usando HELM_GITHUB_USER y HELM_GITHUB_TOKEN
      - name: Configure Git for push
        run: |
          git config user.name "${{ secrets.HELM_GITHUB_USER }}"
          git config user.email "${{ secrets.HELM_GITHUB_USER }}@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.HELM_GITHUB_USER }}:${{ secrets.HELM_GITHUB_TOKEN }}@github.com/luismuma/techwave_web_K8s.git

      # 7. Commit y push del cambio
      - name: Commit updated values.yaml
        run: |
          git add $GITHUB_WORKSPACE/helm/flask-app/values.yaml
          git commit -m "chore: update Docker image to $IMAGE_TAG" || echo "No changes to commit"
          git push origin main

      # 8. Verificar imagen construida (opcional)
      - name: Verify Docker image
        run: docker images
