name: Build and Deploy Docker Image
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         persist-credentials: true   # permite push con GITHUB_TOKEN

      # 2. Login a Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir imagen con tag dinámico (SHA corto)
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}   # 8 primeros caracteres del SHA
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Push de la imagen al Docker Hub
      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG

      # 5. Actualizar Helm values.yaml con la nueva versión
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" $GITHUB_WORKSPACE/helm/flask-app/values-green.yaml

      # 6. Commit y push seguro usando HELM_GITHUB_USER y HELM_GITHUB_TOKEN
      - name: Commit and push updated values.yaml
        run: |
          git config user.name "${{ secrets.HELM_GITHUB_USER }}"
          git config user.email "${{ secrets.HELM_GITHUB_USER }}@users.noreply.github.com"
          git add $GITHUB_WORKSPACE/helm/flask-app/values-green.yaml
          git commit -m "chore: update Docker image to $IMAGE_TAG" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # git push https://${{ secrets.HELM_GITHUB_USER }}:${{ secrets.HELM_GITHUB_TOKEN }}@github.com/luismuma/techwave_web_K8s.git main --force || echo "Push failed, but workflow continues"

      # 7. Configurar AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # 7. Configurar kubectl para EKS
      - name: Configure kubectl for EKS
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name eks-demo
          
      # 8 Verificar imagen construida (opcional)
      - name: Verify Docker image
        run: |
          echo "Verifying built Docker image with tag $IMAGE_TAG"
          docker images lumuma2025/techwave_web_k8s:$IMAGE_TAG
          
      # 9. deploy with helm
      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app-green ./helm/flask-app \
             -f helm/flask-app/values-green.yaml \
             --set image.repository=lumuma2025/techwave_web_k8s \
             --set image.tag=$IMAGE_TAG
             
