name: Build and Deploy Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar c칩digo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir imagen con tag din치mico (commit SHA)
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}  # 8 primeros caracteres del SHA
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Push imagen al registry
      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG
      # 4.15. ruta Helm values.yaml con la nueva versi칩n
      - name: List repo files
        run: ls -R $GITHUB_WORKSPACE
        
      # 5. Actualizar Helm values.yaml con la nueva versi칩n
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" $GITHUB_WORKSPACE/helm/flask-app/values.yaml

      - name: Configure Git for push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/luismuma/techwave_web_K8s.git

      # 6. Commit y push del cambio a Git
      - name: Commit updated values.yaml
        run: |
          git add flask-app/values.yaml
          git commit -m "chore: update Docker image to $IMAGE_TAG"
          git push origin main

      # 7. Verificar imagen construida (opcional)
      - name: Verify Docker image
        run: docker images
  
