name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. Login Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build image con SHA corto
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Push image
      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG

      # 5. Update Helm values.yaml
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" helm/flask-app/values-green.yaml

      # 6. Commit & push (dispara ArgoCD)
      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add helm/flask-app/values-green.yaml
          git commit -m "chore: update Docker image to $IMAGE_TAG" || echo "No changes"
          git push origin main || echo "No changes"
